apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: microdrive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16
        env:
        - name: POSTGRES_PASSWORD
          value: "qwerty"
        ports:
        - containerPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: microdrive
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432