apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: microdrive
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 44044
      targetPort: 44044
  type: ClusterIP
