apiVersion: v1
kind: Service
metadata:
  name: storage-service
  namespace: microdrive
spec:
  selector:
    app: storage
  ports:
    - protocol: TCP
      port: 55055
      targetPort: 55055
  type: ClusterIP
